---
version: "3"  

networks:
  frontend:
    external: true

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./data:/data
    # ports:
    #   - 50080:80
    #   - 50443:443
    restart: unless-stopped
    networks:
      - frontend  