---
version: "3"

networks:
  frontend:
    external: true

services:
  speedtest:
    image: "ghcr.io/alexjustesen/speedtest-tracker:latest"
    container_name: speedtest
    env_file:
      - ../.shared.env
    volumes:
      - "/etc/localtime:/etc/localtime"
      - ./config:/config
    # ports:
    #   - 80:80
    #   - 443:443
    restart: unless-stopped
    networks:
      - frontend
