---
version: "3"  

networks:
  frontend:
    external: true

services:
  speedtest:
    image: 'ghcr.io/alexjustesen/speedtest-tracker:latest'
    container_name: speedtest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - '/etc/localtime:/etc/localtime'
      - ./config:/config
    # ports:
    #   - 80:80
    #   - 443:443
    restart: unless-stopped
    networks:
      - frontend