---
version: "3"  

networks:
  frontend:
    external: true

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config:/config
      - ./data:/data
    # ports:
    #   - 443:443
    restart: unless-stopped
    networks:
      - frontend