---
version: "3"

networks:
  frontend:
    external: true

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    env_file:
      - ../.shared.env
    volumes:
      - ./config:/config
      - ./data:/data
    # ports:
    #   - 443:443
    restart: unless-stopped
    networks:
      - frontend
