version: "3"

networks:
  frontend:
    external: true

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    # ports:
    #   - 9443:9443 # Web UI
    env_file:
      - ../.shared.env
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - frontend
