---
version: "3"

networks:
  frontend:
    external: true

services:
  syncthing:
    image: syncthing/syncthing	
    container_name: syncthing
    hostname: pi-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - ./config:/var/syncthing/config
      - ~/syncthing:/var/syncthing/Sync
    ports:
      # - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
    networks:
      - frontend