version: "3.9"

networks:
  frontend:
    external: true
  monica-backend:
    name: monica-backend

services:
  monica:
    image: monica
    container_name: monica
    env_file:
      - ../.shared.env
    depends_on:
      - monica-db
    ports:
      - 8080:80
    volumes:
      - ./data-monica:/var/www/html/storage
    restart: unless-stopped
    networks:
      - frontend
      - monica-backend

  monica-cron:
    image: monica
    container_name: monica-cron
    env_file:
      - ../.shared.env
    restart: unless-stopped
    volumes:
      - ./data:/var/www/html/storage
    command: cron.sh
    depends_on:
      - monica-db
    networks:
      - monica-backend

  monica-db:
    image: tobi312/rpi-mariadb:10.6-alpine
    container_name: monica-db
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/mysql:rw
    env_file:
      - ../.shared.env
      - .env
    # ports:
    #   - 3306:3306
    networks:
      - monica-backend
